language: node_js
node_js:
  - '5.5'
  - '4.2'
  - '0.12'
before_script:
  - 'npm run lint'
after_script:
  - 'npm run coverage'
  - 'npm run cobertura'
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: npm
  email: $EMAIL_ADDRESS
  api_key: $NPM_API_KEY
  on:
    tags: true
    all_branches: true
